#!/usr/bin/env python
"""
Sanchar AI - Quick Setup Script
Automated installation and configuration
"""

import os
import sys
import subprocess
import platform

def print_header(text):
    """Print formatted header"""
    print("\n" + "="*60)
    print(f"  {text}")
    print("="*60 + "\n")

def run_command(command, description):
    """Run a shell command with error handling"""
    print(f"⚙️  {description}...")
    try:
        result = subprocess.run(command, shell=True, check=True, 
                               capture_output=True, text=True)
        print(f"✅ {description} - Success")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ {description} - Failed")
        print(f"   Error: {e.stderr}")
        return False

def check_python_version():
    """Check if Python version is compatible"""
    print_header("Checking Python Version")
    version = sys.version_info
    print(f"Python {version.major}.{version.minor}.{version.micro}")
    
    if version.major < 3 or (version.major == 3 and version.minor < 8):
        print("❌ Python 3.8+ required")
        print("   Please upgrade Python and try again")
        return False
    
    print("✅ Python version compatible")
    return True

def create_virtual_environment():
    """Create Python virtual environment"""
    print_header("Creating Virtual Environment")
    
    if os.path.exists('venv'):
        print("⚠️  Virtual environment already exists")
        response = input("   Recreate? (y/n): ").lower()
        if response == 'y':
            if platform.system() == "Windows":
                run_command("rmdir /s /q venv", "Removing old venv")
            else:
                run_command("rm -rf venv", "Removing old venv")
        else:
            print("✅ Using existing venv")
            return True
    
    return run_command("python -m venv venv", "Creating virtual environment")

def activate_venv_command():
    """Get the command to activate virtual environment"""
    if platform.system() == "Windows":
        return "venv\\Scripts\\activate"
    else:
        return "source venv/bin/activate"

def install_dependencies():
    """Install Python dependencies"""
    print_header("Installing Dependencies")
    
    # Determine pip command
    if platform.system() == "Windows":
        pip_cmd = "venv\\Scripts\\pip"
    else:
        pip_cmd = "venv/bin/pip"
    
    commands = [
        (f"{pip_cmd} install --upgrade pip", "Upgrading pip"),
        (f"{pip_cmd} install -r requirements.txt", "Installing packages")
    ]
    
    for cmd, desc in commands:
        if not run_command(cmd, desc):
            return False
    
    return True

def setup_environment():
    """Setup .env file"""
    print_header("Setting Up Environment Variables")
    
    if os.path.exists('.env'):
        print("⚠️  .env file already exists")
        response = input("   Overwrite? (y/n): ").lower()
        if response != 'y':
            print("✅ Keeping existing .env")
            return True
    
    print("\n📝 Please provide your API keys (press Enter to skip):\n")
    
    google_maps = input("   Google Maps API Key: ").strip()
    openrouter = input("   OpenRouter API Key (optional): ").strip()
    gee_project = input("   Google Earth Engine Project (optional): ").strip()
    
    env_content = f"""# Sanchar AI Configuration
# Generated by setup script

# Required
GOOGLE_MAPS_API_KEY={google_maps if google_maps else "your_google_maps_api_key_here"}

# Optional (fallback methods available)
OPENROUTER_API_KEY={openrouter if openrouter else "your_openrouter_api_key_here"}
GOOGLE_EARTH_ENGINE_PROJECT={gee_project if gee_project else "your_gee_project_id"}
GOOGLE_EARTH_ENGINE_KEY_PATH=service-account-key.json

# Security
SECRET_KEY={"".join([chr((i*7 + 13) % 26 + 97) for i in range(32)])}

# Database
DATABASE_URL=sqlite:///sanchar_ai.db
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("✅ Environment file created")
    return True

def initialize_database():
    """Initialize database"""
    print_header("Initializing Database")
    
    # Determine python command
    if platform.system() == "Windows":
        python_cmd = "venv\\Scripts\\python"
    else:
        python_cmd = "venv/bin/python"
    
    if not run_command(f"{python_cmd} migrate_database.py", 
                      "Running database migrations"):
        return False
    
    print("\n📊 Generate demo data?")
    response = input("   (Recommended for testing) (y/n): ").lower()
    
    if response == 'y':
        return run_command(f"{python_cmd} demo_data_generator.py",
                          "Generating demo data")
    
    return True

def print_next_steps():
    """Print instructions for next steps"""
    print_header("Setup Complete! 🎉")
    
    activate_cmd = activate_venv_command()
    
    if platform.system() == "Windows":
        python_cmd = "venv\\Scripts\\python"
    else:
        python_cmd = "venv/bin/python"
    
    print("""
✅ Sanchar AI is ready to run!

📋 Next Steps:

1. Activate virtual environment:
   
   {}

2. Start the application:
   
   {} app.py

3. Open your browser:
   
   http://localhost:5000

4. Register an account and explore features!

📚 Documentation:

   - README_NEW.md          - Complete setup guide
   - COMPREHENSIVE_FEATURES.md - Detailed feature docs
   - DEMO_GUIDE.md         - Presentation guide

🔑 API Keys:

   - Edit .env file to add/update API keys
   - Google Maps API is required
   - OpenRouter & Earth Engine are optional

⚠️  Troubleshooting:

   - If camera doesn't work, check browser permissions
   - For slow detection, reduce video resolution
   - Check logs in terminal for errors

💡 Tips:

   - Start with demo data to explore features
   - Try map dashboard first for overview
   - Test live detection with webcam
   - Check COMPREHENSIVE_FEATURES.md for API testing

🚀 Ready to make roads safer!

""".format(activate_cmd, python_cmd))

def main():
    """Main setup function"""
    print("""
    
  ███████╗ █████╗ ███╗   ██╗ ██████╗██╗  ██╗ █████╗ ██████╗ 
  ██╔════╝██╔══██╗████╗  ██║██╔════╝██║  ██║██╔══██╗██╔══██╗
  ███████╗███████║██╔██╗ ██║██║     ███████║███████║██████╔╝
  ╚════██║██╔══██║██║╚██╗██║██║     ██╔══██║██╔══██║██╔══██╗
  ███████║██║  ██║██║ ╚████║╚██████╗██║  ██║██║  ██║██║  ██║
  ╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
                                                              
            Intelligent Traffic Management System
                    Quick Setup Script
    
    """)
    
    # Run setup steps
    steps = [
        (check_python_version, "Python version check"),
        (create_virtual_environment, "Virtual environment"),
        (install_dependencies, "Dependency installation"),
        (setup_environment, "Environment configuration"),
        (initialize_database, "Database initialization")
    ]
    
    for step_func, step_name in steps:
        try:
            if not step_func():
                print(f"\n❌ Setup failed at: {step_name}")
                print("   Please check errors above and try again")
                return 1
        except Exception as e:
            print(f"\n❌ Unexpected error in {step_name}: {e}")
            return 1
    
    print_next_steps()
    return 0

if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Fatal error: {e}")
        sys.exit(1)
